# Generated by Django 5.0.3 on 2024-03-13 18:05

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.AddField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='title',
            field=models.CharField(default='Не заполнено', max_length=100, verbose_name='название привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.IntegerField(default=120, validators=[habits.validators.validate_execution_time], verbose_name='Время выполнения (в секундах)'),
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Привычка')),
            ],
        ),
    ]
